// <auto-generated> This file has been auto generated by CSharp.OpenSource.LinqToKql.ORMGen.ORMGenerator. </auto-generated>
// <auto-generated> database('TestDatabase1').SampleTable </auto-generated>
#pragma warning disable IDE1006 // Naming Styles
#nullable enable
using System;

namespace AutoGenE2E;

public partial class SampleTable
{
    public virtual int? Id { get; set; }
    public virtual string? Name { get; set; }
    public virtual DateTime? Date { get; set; }
    public virtual DateTime? DateOnly { get; set; }
    public virtual TimeSpan? TimeOnly { get; set; }
    public virtual TimeSpan? Time { get; set; }
    public virtual bool? IsActive { get; set; }
    public virtual int? Year { get; set; }
    public virtual string? Description { get; set; }
    public virtual string? Type { get; set; }
    public virtual long? Value { get; set; }
    public virtual object? Numbers { get; set; }
    public virtual object? Nested { get; set; }
}