// <auto-generated> This file has been auto generated by CSharp.OpenSource.LinqToKql.ORMGen.ORMGenerator. </auto-generated>
// <auto-generated> database('TestDatabase1').TestTable </auto-generated>
#pragma warning disable IDE1006 // Naming Styles
#nullable enable
using System;

namespace AutoGenE2E;

public partial class TestTable
{
    public virtual string? TestColumn { get; set; }
}