// <auto-generated> This file has been auto generated by CSharp.OpenSource.LinqToKql.ORMGen.ORMGenerator. </auto-generated>
// <auto-generated> database('TestDatabase2').func2(name: string, lastName: string) </auto-generated>
#pragma warning disable IDE1006 // Naming Styles
#nullable enable
using System;

namespace AutoGen;

public partial class func2
{
    public virtual string? userName { get; set; }
    public virtual string? userLastName { get; set; }
}