// <auto-generated> This file has been auto generated by CSharp.OpenSource.LinqToKql.ORMGen.ORMGenerator. </auto-generated>
// <auto-generated> database('TestDatabase1').func1 </auto-generated>
#pragma warning disable IDE1006 // Naming Styles
#nullable enable
using System;

namespace AutoGen;

public partial class func1
{
    public virtual string? name { get; set; }
}