// <auto-generated> This file has been auto generated by CSharp.OpenSource.LinqToKql.ORMGen.ORMGenerator. </auto-generated>
// <auto-generated> database('TestDatabase2').TestTable1 </auto-generated>
#pragma warning disable IDE1006 // Naming Styles
#nullable enable
using System;

namespace AutoGenE2E;

public partial class TestTable1
{
    public virtual string? userName { get; set; }
    public virtual string? userLastName { get; set; }
}